services:
  # --- Backend Laravel ---
  api:
    build:
      context: ./backend/vendor/laravel/sail/runtimes/8.5
      dockerfile: Dockerfile
      args:
        WWWGROUP: ${WWWGROUP:-1000}
    container_name: backend
    image: 'sail-8.5/app'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - "8000:80"
    environment:
      WWWUSER: ${WWWUSER:-1000}
      LARAVEL_SAIL: 1
    volumes:
      - './backend:/var/www/html'
    networks:
      - food-network
    depends_on:
      db: { condition: service_healthy }
      redis: { condition: service_healthy }
    env_file:
      - ./backend/.env

  # --- Bancos e Serviços ---
  db:
    image: 'postgres:15'
    container_name: food-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: food_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - food-postgres:/var/lib/postgresql/data
    networks:
      - food-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d food_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    container_name: food-redis
    image: redis:alpine
    networks:
      - food-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s
    volumes:
      - redis_data:/data

  mailpit:
    image: 'axllent/mailpit:latest'
    container_name: food-mailpit
    ports:
      - "8025:8025"
    networks:
      - food-network

  # --- Frontends ---
  admin-dashboard:
    image: food-admin-image:latest
    build:
      context: ./admin-dashboard
      dockerfile: Dockerfile.dev
    container_name: food-admin
    volumes:
      - ./admin-dashboard:/app
      - /app/node_modules
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "80"]
    ports:
      - "5175:80"
    networks:
      - food-network
    depends_on:
      - api

  customer-app:
    image: food-customer-image:latest
    build:
      context: ./customer-app
      dockerfile: Dockerfile
    container_name: food-customer
    volumes:
      - ./customer-app:/app
      - /app/node_modules
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "80"]
    ports:
      - "5174:80"
    networks:
      - food-network
    depends_on:
      - api

networks:
  food-network:
    driver: bridge

volumes:
  food-postgres:
  redis_data: