apiVersion: v1
kind: Namespace
metadata:
  name: partiumenu
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: partiumenu-config
  namespace: partiumenu
data:
  APP_NAME: "PartiuMenu"
  APP_ENV: "production"
  APP_DEBUG: "false"
  APP_URL: "https://api.partiumenu.com.br"
  APP_MENU_URL: "https://app.partiumenu.com.br"
  ADMIN_DASHBOARD_URL: "https://admin.partiumenu.com.br"
  FRONTEND_URL: "https://app.partiumenu.com.br"
  APP_FRONTEND_URL: "https://partiumenu.com.br"
  APP_TIMEZONE: "America/Fortaleza"
  APP_LOCALE: "pt_BR"
  APP_FALLBACK_LOCALE: "pt_BR"
  LOG_CHANNEL: "stderr"
  LOG_LEVEL: "info"

  DB_CONNECTION: "pgsql"
  DB_HOST: "postgres.data.svc.cluster.local"
  DB_PORT: "5432"
  DB_DATABASE: "food"
  DB_USERNAME: "platform"
  DB_SSLMODE: "prefer"

  QUEUE_CONNECTION: "database"
  SESSION_DRIVER: "database"
  CACHE_STORE: "database"
  MEDIA_DISK: "s3"
  AWS_DEFAULT_REGION: "auto"
  AWS_USE_PATH_STYLE_ENDPOINT: "true"

  KAFKA_ENABLED: "true"
  KAFKA_BROKERS: "kafka-service.data.svc.cluster.local:9092"
  KAFKA_SECURITY_PROTOCOL: "PLAINTEXT"
  KAFKA_CONSUMER_GROUP_ID: "partiumenu-ai-consumer"
  KAFKA_TOPIC_WHATSAPP_INBOUND: "whatsapp.inbound.messages"
  KAFKA_TOPIC_WHATSAPP_OUTBOUND: "whatsapp.outbound.messages"
  KAFKA_TOPIC_ORDERS: "orders.lifecycle.events"
  KAFKA_TOPIC_IFOOD: "ifood.incoming.events"

  SANCTUM_STATEFUL_DOMAINS: "admin.partiumenu.com.br,app.partiumenu.com.br,partiumenu.com.br,www.partiumenu.com.br"
  SESSION_DOMAIN: ".partiumenu.com.br"

  BROADCAST_CONNECTION: "pusher"
  PUSHER_APP_CLUSTER: "ap3"
  PUSHER_PORT: "443"
  PUSHER_SCHEME: "https"

  MAIL_MAILER: "smtp"
  MAIL_HOST: "smtp-relay.brevo.com"
  MAIL_PORT: "587"
  MAIL_ENCRYPTION: "tls"
  MAIL_FROM_ADDRESS: "noreply@partiumenu.com.br"
  MAIL_FROM_NAME: "Partiu Menu"

  WHATSAPP_AI_PROVIDER: "gemini"
  GEMINI_ENABLED: "true"
  GEMINI_MODEL: "gemini-2.5-flash"
  GEMINI_TIMEOUT: "20"
  IFOOD_BASE_URL: "https://merchant-api.ifood.com.br"
  IFOOD_ENVIRONMENT: "production"
  IFOOD_TIMEOUT: "20"
